# GenomeAI Enhanced Configuration File
# Production-ready bioinformatics pipeline with pharmacogenomics, MTHFR, disease risk, and traits analysis

# General settings
threads: 8
temp_dir: "/tmp/genomeai"
log_level: "INFO"

# Reference genome settings
reference:
  genome: "/path/to/GRCh38.fa"  # Update with actual path
  gtf: "/path/to/gencode.v44.annotation.gtf"  # Update with actual path

# Quality control settings
qc:
  min_quality: 20
  min_length: 50
  fastp_params:
    - "--detect_adapter_for_pe"
    - "--correction"
    - "--cut_front"
    - "--cut_tail"
    - "--cut_window_size=4"
    - "--cut_mean_quality=20"

# Alignment settings
alignment:
  bwa_params:
    - "-M"  # Mark shorter split hits as secondary
  minimap2_params:
    - "--secondary=no"
    - "-L"  # Use long cigars for better accuracy

# Variant calling settings
variant_calling:
  min_base_quality: 20
  min_mapping_quality: 20
  min_alt_fraction: 0.2
  min_coverage: 4
  additional_params:
    - "--use-best-n-alleles=4"
    - "--min-alternate-count=2"
  
  # GATK settings (for future use)
  gatk:
    stand_call_conf: 30
    additional_params:
      - "--dont-use-soft-clipped-bases"

# Variant filtering settings
variant_filtering:
  min_depth: 10
  min_gq: 20
  min_qual: 30
  max_missing: 0.1
  apply_hard_filters: false
  
  # Custom filter expressions
  custom_filters:
    - "FORMAT/DP >= 10"
    - "QUAL >= 30"
  
  # Hard filters (GATK VariantFiltration)
  hard_filters:
    QualByDepth: "QD < 2.0"
    FisherStrand: "FS > 60.0"
    RMSMappingQuality: "MQ < 40.0"
    MappingQualityRankSum: "MQRankSum < -12.5"
    ReadPosRankSum: "ReadPosRankSum < -8.0"

# Annotation settings
annotation:
  vep:
    cache_dir: "/path/to/vep_cache"  # Update with actual path
    species: "homo_sapiens"
    assembly: "GRCh38"
    
    # VEP plugins
    plugins:
      - "CADD,/path/to/CADD.tsv.gz"
      - "dbNSFP,/path/to/dbNSFP.txt.gz,ALL"
    
    # Custom annotations
    custom:
      - "/path/to/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN"
      - "/path/to/gnomad.vcf.gz,gnomAD,vcf,exact,0,AF,AF_popmax"
    
    # Output fields
    fields:
      - "Uploaded_variation"
      - "Location"
      - "Allele"
      - "Gene"
      - "Feature"
      - "Feature_type"
      - "Consequence"
      - "cDNA_position"
      - "CDS_position"
      - "Protein_position"
      - "Amino_acids"
      - "Codons"
      - "Existing_variation"
      - "IMPACT"
      - "DISTANCE"
      - "STRAND"
      - "FLAGS"
      - "SYMBOL"
      - "BIOTYPE"
      - "CANONICAL"
    
    additional_params:
      - "--everything"
      - "--check_existing"
      - "--pick"  # Pick one consequence per variant

# RNA-seq settings
rna:
  salmon:
    index_path: "/path/to/salmon_index"  # Update with actual path
    transcriptome_fasta: "/path/to/transcriptome.fa"  # Update with actual path
    kmer_length: 31
    bootstrap_samples: 100
    
    index_params:
      - "--type=quasi"
      - "--keepDuplicates"
    
    additional_params:
      - "--validateMappings"
      - "--gcBias"
      - "--seqBias"
      - "--posBias"
  
  # Transcript to gene mapping
  tx2gene_mapping: "/path/to/tx2gene.tsv"  # Update with actual path

# AI Explanation settings
explain:
  # FAISS index settings
  index_dir: "faiss_index"
  embedding_model: "all-MiniLM-L6-v2"
  
  # ClinVar data
  clinvar_file: "/path/to/clinvar_summary.txt"  # Update with actual path
  
  # Retrieval settings
  num_similar_variants: 5
  min_similarity_threshold: 0.5
  max_variants_to_explain: 100
  exclude_uncertain: false
  
  required_fields:
    - "gene"
    - "clinical_significance"
  
  # Local LLM settings
  llm:
    model_path: "/path/to/llama-model.gguf"  # Update with actual path
    context_length: 2048
    max_tokens: 300
    temperature: 0.7
    threads: 4

# Enhanced Analysis Modules Configuration
pharmacogenomics:
  enabled: true
  
  # PharmGKB data settings
  pharmgkb:
    data_file: "/path/to/pharmgkb_data.json"  # Update with actual path
    api_key: ""  # Optional API key for PharmGKB
  
  # CPIC guidelines
  cpic:
    guidelines_file: "/path/to/cpic_guidelines.json"  # Update with actual path
  
  # Genes to analyze
  target_genes:
    - "CYP2D6"
    - "CYP2C19"
    - "CYP3A4"
    - "TPMT"
    - "DPYD"
    - "SLCO1B1"
    - "UGT1A1"
    - "VKORC1"
  
  # Drug categories to focus on
  drug_categories:
    - "cardiovascular"
    - "psychiatric"
    - "oncology"
    - "immunosuppressants"
    - "anticoagulants"

mthfr:
  enabled: true
  
  # MTHFR variants to analyze
  variants:
    c677t:
      rsid: "rs1801133"
      chromosome: "1"
      position: 11796321  # GRCh38
    a1298c:
      rsid: "rs1801131"
      chromosome: "1"
      position: 11794419  # GRCh38
  
  # Risk assessment thresholds
  risk_levels:
    low: "No variants or single heterozygous variant"
    mild: "Single heterozygous variant with mild effect"
    moderate: "Compound heterozygous or single homozygous mild variant"
    high: "Homozygous C677T or compound heterozygous high-risk"

disease_risk:
  enabled: true
  
  # High-priority disease genes
  cancer_genes:
    - "BRCA1"
    - "BRCA2"
    - "TP53"
    - "APC"
    - "MLH1"
    - "MSH2"
    - "MSH6"
    - "PMS2"
    - "PALB2"
    - "ATM"
    - "CHEK2"
  
  cardiovascular_genes:
    - "LDLR"
    - "PCSK9"
    - "APOB"
    - "MYBPC3"
    - "MYH7"
    - "TNNT2"
    - "TNNI3"
  
  neurological_genes:
    - "APOE"
    - "HTT"
    - "SNCA"
    - "LRRK2"
    - "PARK7"
    - "PINK1"
    - "PRKN"
  
  metabolic_genes:
    - "HFE"
    - "PAH"
    - "CFTR"
    - "GBA"
    - "HEXA"
    - "SMN1"
  
  # Clinical significance thresholds
  significance_levels:
    pathogenic: ["Pathogenic", "Likely pathogenic"]
    uncertain: ["Uncertain significance", "VUS"]
    benign: ["Benign", "Likely benign"]

traits_ancestry:
  enabled: true
  
  # Physical traits
  physical_traits:
    eye_color:
      - "rs12913832"  # HERC2
      - "rs1800407"   # OCA2
    hair_color:
      - "rs1805007"   # MC1R
      - "rs1805008"   # MC1R
      - "rs1110400"   # MC1R
    skin_pigmentation:
      - "rs1426654"   # SLC24A5
      - "rs16891982"  # SLC45A2
  
  # Nutritional genomics
  nutritional_markers:
    lactose_intolerance:
      - "rs4988235"   # LCT
    caffeine_metabolism:
      - "rs762551"    # CYP1A2
    alcohol_metabolism:
      - "rs1229984"   # ADH1B
      - "rs671"       # ALDH2
    folate_metabolism:
      - "rs1801133"   # MTHFR C677T
      - "rs1801131"   # MTHFR A1298C
    vitamin_d_metabolism:
      - "rs2282679"   # GC
    iron_metabolism:
      - "rs1799945"   # HFE H63D
  
  # Ancestry informative markers
  ancestry_markers:
    european:
      - "rs16891982"  # SLC45A2
      - "rs1426654"   # SLC24A5
      - "rs12913832"  # HERC2
    african:
      - "rs2814778"   # DARC
      - "rs334"       # HBB
      - "rs1800562"   # HFE
    asian:
      - "rs671"       # ALDH2
      - "rs17822931"  # ABCC11
      - "rs3827760"   # EDAR
    native_american:
      - "rs9939609"   # FTO
      - "rs1815739"   # ACTN3

# Enhanced reporting settings
enhanced_reporting:
  enabled: true
  
  # Report formats
  formats:
    - "markdown"
    - "html"
    - "json"
  
  # Individual module reports
  individual_reports:
    pharmacogenomics: true
    mthfr: true
    disease_risk: true
    traits_ancestry: true
  
  # Comprehensive report
  comprehensive_report:
    enabled: true
    include_disclaimers: true
    include_recommendations: true
    include_variant_details: true
  
  # Report styling
  styling:
    theme: "professional"
    include_charts: false  # Set to true when visualization is implemented
    include_tables: true

# Output settings
output:
  compress_vcf: true
  create_index: true
  save_intermediate: false
  
  # File formats
  formats:
    variants: ["vcf.gz", "parquet", "tsv"]
    annotations: ["parquet", "tsv", "json"]
    reports: ["html", "markdown", "json"]

# Resource limits
resources:
  max_memory_gb: 32
  max_disk_gb: 100
  timeout_hours: 24

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "genomeai.log"
  max_size_mb: 100
  backup_count: 5

# Database paths (update these with actual paths)
databases:
  clinvar: "/path/to/clinvar.vcf.gz"
  gnomad: "/path/to/gnomad.genomes.vcf.gz"
  dbsnp: "/path/to/dbsnp.vcf.gz"
  cadd: "/path/to/CADD_GRCh38.tsv.gz"
  dbnsfp: "/path/to/dbNSFP4.4a.txt.gz"
  pharmgkb: "/path/to/pharmgkb_variants.tsv"
  cpic: "/path/to/cpic_guidelines.tsv"

# Tool paths (usually auto-detected, specify if needed)
tools:
  fastp: "fastp"
  bwa_mem2: "bwa-mem2"
  minimap2: "minimap2"
  samtools: "samtools"
  bcftools: "bcftools"
  freebayes: "freebayes"
  gatk: "gatk"
  vep: "vep"
  salmon: "salmon"
  tabix: "tabix"
  bgzip: "bgzip"

# Validation settings
validation:
  check_tools: true
  check_references: true
  check_databases: false  # Set to true in production
  strict_mode: false

# Performance tuning
performance:
  chunk_size: 1000000  # For large file processing
  parallel_jobs: 4
  memory_per_job: "8G"
  use_tmp_disk: true

# Module enablement (allow users to enable/disable specific analyses)
modules:
  basic_pipeline: true      # Core DNA/RNA analysis
  pharmacogenomics: true    # Drug-gene interactions
  mthfr: true              # MTHFR variant analysis
  disease_risk: true        # Disease predisposition
  traits_ancestry: true     # Physical traits and ancestry
  enhanced_reporting: true  # Comprehensive reports